SET CURRENT SCHEMA DICDAT;

CREATE TABLE
    DICDAT.TBL_DICDAT_INS_CATA
    (   
        INS_ID_CD VARCHAR(16) NOT NULL WITH DEFAULT,
        INS_CN_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        ROOT_INS_CD VARCHAR(16) NOT NULL WITH DEFAULT,
        ROOT_INS_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        CUP_BRANCH_CD VARCHAR(16) NOT NULL WITH DEFAULT,
        CUP_BRANCH_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        INS_CATA_1ST_ID INTEGER NOT NULL WITH DEFAULT,
        INS_CATA_1ST_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        INS_CATA_2ND_ID INTEGER NOT NULL WITH DEFAULT,
        INS_CATA_2ND_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        INS_CATA_3RD_ID INTEGER NOT NULL WITH DEFAULT,
        INS_CATA_3RD_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        INS_CATA_4TH_ID INTEGER NOT NULL WITH DEFAULT,
        INS_CATA_4TH_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        CONSTRAINT IND_DICDAT_AT_PK PRIMARY KEY (INS_ID_CD)
    );

--CREATE INDEX DICDAT.IND_DICDAT_AT_I1
--ON DICDAT.TBL_DICDAT_INS_CATA (
--        MCHNT_CD
--        ,AUDIT_ST
--    )
--;


GRANT ALL ON DICDAT.TBL_DICDAT_INS_CATA TO USER OP_MGMAP;
GRANT SELECT ON DICDAT.TBL_DICDAT_INS_CATA TO USER OP_MGMMN;
