SET CURRENT SCHEMA MMGM;

CREATE TABLE
    MMGM.TBL_MMGM_BATCH_MCHNT_INFO
    (   
        MCHNT_SRV_TP CHARACTER(2) DEFAULT ' ' NOT NULL,
        MCHNT_CD CHARACTER(15) DEFAULT ' ' NOT NULL,
        MCHNT_CN_ABBR VARCHAR(100) DEFAULT '' NOT NULL,
        MCHNT_CN_NM VARCHAR(100) DEFAULT '' NOT NULL,
        ACQ_INS_ID_CD VARCHAR(11) DEFAULT '' NOT NULL,
        ACPT_INS_ID_CD VARCHAR(11) DEFAULT '' NOT NULL,
        FWD_INS_ID_CD VARCHAR(11) DEFAULT '' NOT NULL,
        CUP_BRANCH_INS_ID_CD VARCHAR(11) DEFAULT '' NOT NULL,
        CONN_MD CHARACTER(1) DEFAULT ' ' NOT NULL,
        MCHNT_TP CHARACTER(4) DEFAULT ' ' NOT NULL,
        SPEC_DISC_TP CHARACTER(2) DEFAULT ' ' NOT NULL,
        SPEC_DISC_LVL CHARACTER(1) DEFAULT ' ' NOT NULL,
        IS_WHITE_MCHNT CHARACTER(1) DEFAULT ' ' NOT NULL,
        D_ALLOT_CD CHARACTER(5) DEFAULT ' ' NOT NULL,
        C_ALLOT_CD CHARACTER(5) DEFAULT ' ' NOT NULL,
        MCHNT_MEMO VARCHAR(128) DEFAULT '' NOT NULL,
        CONSTRAINT IND_MMGM_BMI_PK PRIMARY KEY (MCHNT_CD)
    );

--CREATE INDEX MMGM.IND_MMGM_AT_I1
--ON MMGM.TBL_MMGM_BATCH_MCHNT_INFO (
--        MCHNT_CD
--        ,AUDIT_ST
--    )
--;


GRANT ALL ON MMGM.TBL_MMGM_BATCH_MCHNT_INFO TO USER OP_MGMAP;
GRANT SELECT ON MMGM.TBL_MMGM_BATCH_MCHNT_INFO TO USER OP_MGMMN;
