SET CURRENT SCHEMA MGMHIS;

CREATE TABLE
    MGMHIS.TBL_MGMHIS_REJECT_MCHNT
    (   
        MCHNT_SRV_TP CHARACTER(2) NOT NULL WITH DEFAULT,
        MCHNT_CD CHARACTER(15) NOT NULL WITH DEFAULT,
        MCHNT_CN_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        ACQ_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        ACPT_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        CUP_BRANCH_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        CONN_MD CHARACTER(1) NOT NULL WITH DEFAULT,
        MCHNT_TP CHARACTER(4) NOT NULL WITH DEFAULT,
        SPEC_DISC_TP CHARACTER(2) NOT NULL WITH DEFAULT,
        SPEC_DISC_LVL CHARACTER(1) NOT NULL WITH DEFAULT,
        IS_WHITE_MCHNT CHARACTER(1) NOT NULL WITH DEFAULT,
        ACQ_COMMIT_AUDIT_TS TIMESTAMP NOT NULL,
        CUP_BRANCH_AUDITED_TS TIMESTAMP,
        CUP_BRANCH_AUDITOR VARCHAR(32) NOT NULL WITH DEFAULT,
        CUP_1ST_AUDITED_TS TIMESTAMP,
        CUP_1ST_AUDITOR VARCHAR(32) NOT NULL WITH DEFAULT,
        CUP_2ND_AUDITED_TS TIMESTAMP,
        CUP_2ND_AUDITOR VARCHAR(32) NOT NULL WITH DEFAULT,
        ACQ_AUDIT_MEMO VARCHAR(2048) NOT NULL WITH DEFAULT,
        CUP_BRANCH_MEMO VARCHAR(2048) NOT NULL WITH DEFAULT,
        CUP_HEAD_MEMO VARCHAR(2048) NOT NULL WITH DEFAULT,
        REC_CRT_TS TIMESTAMP NOT NULL WITH DEFAULT,
        REC_UPD_TS TIMESTAMP NOT NULL WITH DEFAULT,
        MCHNT_AUDIT_ID CHARACTER(30) NOT NULL WITH DEFAULT,
        EXPORT_TS TIMESTAMP NOT NULL,
        EXISTS_TS TIMESTAMP NOT NULL,
        CONSTRAINT IND_MGMHIS_RM_PK PRIMARY KEY (MCHNT_AUDIT_ID)
    );

CREATE INDEX MGMHIS.IND_MGMHIS_RM_I1
ON MGMHIS.TBL_MGMHIS_REJECT_MCHNT (
    MCHNT_CD ASC
);

GRANT ALL ON MGMHIS.TBL_MGMHIS_REJECT_MCHNT TO USER OP_MGMAP;
GRANT SELECT ON MGMHIS.TBL_MGMHIS_REJECT_MCHNT TO USER OP_MGMMN;
