SET CURRENT SCHEMA MMGM;

CREATE TABLE
    MMGM.TBL_MMGM_AUDIT_TASK
    (   
        TASK_ID VARCHAR(30) NOT NULL WITH DEFAULT,
        TASK_TP CHARACTER(2) NOT NULL WITH DEFAULT,
        TASK_PRI BIGINT NOT NULL WITH DEFAULT,
        TASK_COMMIT_TS TIMESTAMP NOT NULL,
        TASK_COMMIT_USR VARCHAR(32) NOT NULL WITH DEFAULT,
        TASK_ST CHARACTER(1) NOT NULL WITH DEFAULT,
        TASK_RESULT CHARACTER(1) NOT NULL WITH DEFAULT,
        TASK_PLAN_USR VARCHAR(32) NOT NULL WITH DEFAULT,
        TASK_EXEC_USR VARCHAR(32) NOT NULL WITH DEFAULT,
        TASK_ASSIGN_TS TIMESTAMP,
        TASK_PLAN_DONE_TS TIMESTAMP,
        TASK_EXEC_DONE_TS TIMESTAMP,
        MCHNT_SRV_TP CHARACTER(2) NOT NULL WITH DEFAULT,
        MCHNT_CD CHARACTER(15) NOT NULL WITH DEFAULT,
        MCHNT_CN_NM VARCHAR(100) NOT NULL WITH DEFAULT,
        ACQ_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        ACPT_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        CUP_BRANCH_INS_ID_CD VARCHAR(11) NOT NULL WITH DEFAULT,
        CONN_MD CHARACTER(1) NOT NULL WITH DEFAULT,
        MCHNT_TP CHARACTER(4) NOT NULL WITH DEFAULT,
        SPEC_DISC_TP CHARACTER(2) NOT NULL WITH DEFAULT,
        SPEC_DISC_LVL CHARACTER(1) NOT NULL WITH DEFAULT,
        IS_WHITE_MCHNT CHARACTER(1) NOT NULL WITH DEFAULT,
        ACQ_COMMIT_AUDIT_TS TIMESTAMP NOT NULL,
        AUDIT_ST CHARACTER(1) NOT NULL WITH DEFAULT,
        AVOID_USR VARCHAR(32) NOT NULL WITH DEFAULT,
        COMMISSION_TP CHARACTER(4) NOT NULL WITH DEFAULT,
        ACQ_PRI CHARACTER(1) NOT NULL WITH DEFAULT,
        AUDIT_TP_PRI CHARACTER(2) NOT NULL WITH DEFAULT,
        MCHNT_AUDIT_ID CHARACTER(30) NOT NULL WITH DEFAULT,
        REC_CRT_TS TIMESTAMP NOT NULL WITH DEFAULT,
        REC_UPD_TS TIMESTAMP NOT NULL WITH DEFAULT,
        EXPORT_TS TIMESTAMP NOT NULL,
        CONSTRAINT IND_MMGM_AT_PK PRIMARY KEY (TASK_ID)
    );

CREATE INDEX MMGM.IND_MMGM_AT_I1
ON MMGM.TBL_MMGM_AUDIT_TASK (
        MCHNT_CD
        ,AUDIT_ST
    )
;

CREATE INDEX MMGM.IND_MMGM_AT_I2
ON MMGM.TBL_MMGM_AUDIT_TASK (
        TASK_ST
        ,TASK_RESULT
    )
;

CREATE INDEX MMGM.IND_MMGM_AT_I4
ON MMGM.TBL_MMGM_AUDIT_TASK (
        COMMISSION_TP
    )
;

GRANT ALL ON MMGM.TBL_MMGM_AUDIT_TASK TO USER OP_MGMAP;
GRANT SELECT ON MMGM.TBL_MMGM_AUDIT_TASK TO USER OP_MGMMN;
